name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - 'Package.swift'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - 'Package.swift'

jobs:
  test:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.3.app/Contents/Developer"
      GITHUB_MODEL_CACHE: "${{ github.workspace }}/model"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Cache model file
      id: cache-model
      uses: actions/cache@v4
      with:
        path: ./model
        key: model
        
    - name: Run tests
      run: swift test
