name: Test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "Sources/**"
      - "Tests/**"
      - "Package.swift"
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: ["main"]
    paths:
      - "Sources/**"
      - "Tests/**"
      - "Package.swift"

jobs:
  test:
    name: ${{ matrix.test-type }} Tests
    runs-on: macos-15
    strategy:
      matrix:
        test-type: [Llama, MLX]
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.3.app/Contents/Developer"
      TEST_RUNNER_GITHUB_MODEL_CACHE: "${{ github.workspace }}/model_cache"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache model file
        id: cache-model
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/model_cache
          key: model_cache

      - name: Run ${{ matrix.test-type }} tests
        run: TEST_RUNNER_GITHUB_ACTIONS_TEST="${{ matrix.test-type }}" xcodebuild test -scheme LocalLLMClient-Package -destination 'platform=macOS'
