name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - 'Package.swift'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - 'Package.swift'

jobs:
  test:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.3.app/Contents/Developer"
      LOCAL_LLM_PATH: "${{ github.workspace }}/model/SmolLM2-135M-Instruct-Q5_K_M.gguf"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Cache model file
      id: cache-model
      uses: actions/cache@v4
      with:
        path: model/SmolLM2-135M-Instruct-Q5_K_M.gguf
        key: model-SmolLM2-135M-Instruct-Q5_K_M
        
    - name: Download model file
      if: steps.cache-model.outputs.cache-hit != 'true'
      run: |
        mkdir -p model
        wget -O model/SmolLM2-135M-Instruct-Q5_K_M.gguf https://huggingface.co/bartowski/SmolLM2-135M-Instruct-GGUF/resolve/main/SmolLM2-135M-Instruct-Q5_K_M.gguf
        
    - name: Run tests
      run: swift test
